[2023-01-02T11:29:30.948+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.pronostico_extract scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:29:30.957+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.pronostico_extract scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:29:30.958+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:29:30.958+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-02T11:29:30.959+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:29:30.971+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): pronostico_extract> on 2023-01-01 11:29:00+00:00
[2023-01-02T11:29:30.993+0000] {standard_task_runner.py:55} INFO - Started process 68 to run task
[2023-01-02T11:29:31.000+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'pronostico_extract', 'scheduled__2023-01-01T11:29:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmp26ftlwxu']
[2023-01-02T11:29:31.002+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask pronostico_extract
[2023-01-02T11:29:31.093+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.pronostico_extract scheduled__2023-01-01T11:29:00+00:00 [running]> on host 7b186f3dc822
[2023-01-02T11:29:31.170+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=pronostico_extract
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T11:29:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T11:29:00+00:00
[2023-01-02T11:29:32.040+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/pronosticos.py", line 8, in extract
    open('data/pronosticos_etl/extracted.txt','w').write(text)
FileNotFoundError: [Errno 2] No such file or directory: 'data/pronosticos_etl/extracted.txt'
[2023-01-02T11:29:32.056+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nba-dag, task_id=pronostico_extract, execution_date=20230101T112900, start_date=20230102T112930, end_date=20230102T112932
[2023-01-02T11:29:32.092+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 35 for task pronostico_extract ([Errno 2] No such file or directory: 'data/pronosticos_etl/extracted.txt'; 68)
[2023-01-02T11:29:32.150+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-02T11:29:32.210+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-02T11:37:42.583+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.pronostico_extract scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:37:42.607+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.pronostico_extract scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:37:42.609+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:37:42.610+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-02T11:37:42.611+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:37:42.626+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): pronostico_extract> on 2023-01-01 11:29:00+00:00
[2023-01-02T11:37:42.635+0000] {standard_task_runner.py:55} INFO - Started process 74 to run task
[2023-01-02T11:37:42.641+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'pronostico_extract', 'scheduled__2023-01-01T11:29:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmpthy0o2ad']
[2023-01-02T11:37:42.642+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask pronostico_extract
[2023-01-02T11:37:42.891+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.pronostico_extract scheduled__2023-01-01T11:29:00+00:00 [running]> on host 7b186f3dc822
[2023-01-02T11:37:43.015+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=pronostico_extract
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T11:29:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T11:29:00+00:00
[2023-01-02T11:37:43.288+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-02T11:37:43.301+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=nba-dag, task_id=pronostico_extract, execution_date=20230101T112900, start_date=20230102T113742, end_date=20230102T113743
[2023-01-02T11:37:43.351+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-02T11:37:43.414+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
