[2023-01-02T11:52:33.000+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load scheduled__2023-01-01T11:37:00+00:00 [queued]>
[2023-01-02T11:52:33.006+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load scheduled__2023-01-01T11:37:00+00:00 [queued]>
[2023-01-02T11:52:33.007+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:52:33.008+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 6
[2023-01-02T11:52:33.008+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:52:33.021+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load> on 2023-01-01 11:37:00+00:00
[2023-01-02T11:52:33.031+0000] {standard_task_runner.py:55} INFO - Started process 89 to run task
[2023-01-02T11:52:33.041+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'load', 'scheduled__2023-01-01T11:37:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmpxezkbkq3']
[2023-01-02T11:52:33.044+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask load
[2023-01-02T11:52:33.164+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.load scheduled__2023-01-01T11:37:00+00:00 [running]> on host 7b186f3dc822
[2023-01-02T11:52:33.277+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T11:37:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T11:37:00+00:00
[2023-01-02T11:52:33.424+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/team_stats.py", line 363, in load
    all_stats = pd.read_csv('data/all_stats.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data/all_stats.csv'
[2023-01-02T11:52:33.447+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nba-dag, task_id=load, execution_date=20230101T113700, start_date=20230102T115233, end_date=20230102T115233
[2023-01-02T11:52:33.463+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 50 for task load ([Errno 2] No such file or directory: 'data/all_stats.csv'; 89)
[2023-01-02T11:52:33.495+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-02T11:52:33.524+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
