[2023-01-01T20:14:02.199+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load manual__2023-01-01T20:08:31.042915+00:00 [queued]>
[2023-01-01T20:14:02.212+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load manual__2023-01-01T20:08:31.042915+00:00 [queued]>
[2023-01-01T20:14:02.213+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T20:14:02.216+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2023-01-01T20:14:02.218+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T20:14:02.236+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load> on 2023-01-01 20:08:31.042915+00:00
[2023-01-01T20:14:02.300+0000] {standard_task_runner.py:55} INFO - Started process 61 to run task
[2023-01-01T20:14:02.312+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'load', 'manual__2023-01-01T20:08:31.042915+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmpqmww5rjr']
[2023-01-01T20:14:02.315+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask load
[2023-01-01T20:14:02.455+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.load manual__2023-01-01T20:08:31.042915+00:00 [running]> on host 6f6d58c7a637
[2023-01-01T20:14:02.514+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T20:08:31.042915+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-01T20:08:31.042915+00:00
[2023-01-01T20:14:43.365+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-01T20:14:43.424+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 61. PIDs of all processes in the group: [61]
[2023-01-01T20:14:43.433+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 61
[2023-01-01T20:14:43.444+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-01T20:14:43.745+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/team_stats.py", line 629, in load
    pdf.cell(194,10, f'{time0}', 0, 0, 'C')
  File "/opt/airflow/plugins/team_stats.py", line 76, in news
    soup = BeautifulSoup(requests.get(f'https://www.rotoballer.com/player-news/page/{i}?sport=nba').content, 'html.parser')
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-01T20:14:45.721+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nba-dag, task_id=load, execution_date=20230101T200831, start_date=20230101T201402, end_date=20230101T201445
[2023-01-01T20:14:47.030+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task load (Task received SIGTERM signal; 61)
[2023-01-01T20:14:49.431+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=61, status='terminated', exitcode=1, started='20:14:02') (61) terminated with exit code 1
[2023-01-01T20:14:49.453+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-01T20:14:49.695+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
