[2023-01-01T19:57:01.510+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.pronostico manual__2023-01-01T19:46:06.117940+00:00 [queued]>
[2023-01-01T19:57:01.538+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.pronostico manual__2023-01-01T19:46:06.117940+00:00 [queued]>
[2023-01-01T19:57:01.539+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T19:57:01.540+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-01T19:57:01.541+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T19:57:01.562+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): pronostico> on 2023-01-01 19:46:06.117940+00:00
[2023-01-01T19:57:01.598+0000] {standard_task_runner.py:55} INFO - Started process 70 to run task
[2023-01-01T19:57:01.612+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'pronostico', 'manual__2023-01-01T19:46:06.117940+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmpmtou0y4z']
[2023-01-01T19:57:01.613+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask pronostico
[2023-01-01T19:57:01.829+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.pronostico manual__2023-01-01T19:46:06.117940+00:00 [running]> on host b9d509e49129
[2023-01-01T19:57:02.126+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=pronostico
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T19:46:06.117940+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-01T19:46:06.117940+00:00
[2023-01-01T19:57:02.155+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: prediction() missing 1 required positional argument: 'team'
[2023-01-01T19:57:02.190+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nba-dag, task_id=pronostico, execution_date=20230101T194606, start_date=20230101T195701, end_date=20230101T195702
[2023-01-01T19:57:02.209+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task pronostico (prediction() missing 1 required positional argument: 'team'; 70)
[2023-01-01T19:57:02.296+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-01T19:57:02.372+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
